# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 319531753031117274f1fca0d2844ef39c759a029f9a53abb88624263c13b35d8223439604db4e7dd3afa6d646f0a0b1e2bb8019fa7b60966a5fe28866734eec

test:
  secret_key_base: 01ccd63e1eda7f569811403df78bf958e16347c84cbc692e27df08fdcb85f4d284fc206450a7c56c737a76ffe200adb09e8e512966e684feb8d2d1cc17a7d489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
